name = "StructEqualHash"
uuid = "8bd03d06-bfef-4aaf-8250-1a26cbb401bf"
authors = ["matthias314"]
version = "0.1.2"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
